# Generated by Django 4.2.23 on 2025-08-29 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_id", models.CharField(max_length=30, unique=True)),
                ("asin", models.CharField(max_length=20)),
                ("item_name", models.CharField(max_length=255)),
                ("customer_name", models.CharField(blank=True, max_length=255)),
                ("customer_email", models.EmailField(blank=True, max_length=254)),
                ("order_data", models.DateTimeField(blank=True, null=True)),
                (
                    "order_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Return",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rma",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="Return ID"
                    ),
                ),
                ("return_reason", models.CharField(blank=True, max_length=255)),
                ("tracking_id", models.CharField(blank=True, max_length=100)),
                (
                    "return_item_desc",
                    models.TextField(blank=True, verbose_name="Return Item"),
                ),
                ("received_condition", models.CharField(blank=True, max_length=255)),
                ("return_data", models.DateTimeField(blank=True, null=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="returns",
                        to="cases.order",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DisputeCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "reason_code",
                    models.CharField(
                        choices=[
                            ("damaged", "Item is damaged"),
                            ("wrong_item", "Wrong Item Sent"),
                            ("no_return", "Not actually returned"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("details", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("submitted", "Submitted to Amazon"),
                            ("awaiting", "Awaiting Amazon Response"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("closed", "Closed"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                ("amazon_case_id", models.CharField(blank=True, max_length=100)),
                ("resolution_text", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cases",
                        to="cases.order",
                    ),
                ),
                (
                    "returns",
                    models.ManyToManyField(
                        blank=True, related_name="cases", to="cases.return"
                    ),
                ),
            ],
        ),
    ]
