# Generated by Django 4.2.23 on 2025-08-30 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("returns", "0001_initial"),
        ("orders", "0001_initial"),
        ("cases", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="return",
            name="order",
        ),
        migrations.AlterField(
            model_name="disputecase",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cases",
                to="orders.order",
            ),
        ),
        migrations.AlterField(
            model_name="disputecase",
            name="returns",
            field=models.ManyToManyField(
                blank=True, related_name="cases", to="returns.return"
            ),
        ),
        migrations.DeleteModel(
            name="Order",
        ),
        migrations.DeleteModel(
            name="Return",
        ),
    ]
