# Generated by Django 4.2.23 on 2025-08-30 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Return",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rma",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="Return ID"
                    ),
                ),
                ("return_reason", models.CharField(blank=True, max_length=255)),
                ("tracking_id", models.CharField(blank=True, max_length=100)),
                (
                    "return_item_desc",
                    models.TextField(blank=True, verbose_name="Return Item"),
                ),
                ("received_condition", models.CharField(blank=True, max_length=255)),
                ("return_data", models.DateTimeField(blank=True, null=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="returns",
                        to="orders.order",
                    ),
                ),
            ],
        ),
    ]
