# Generated by Django 4.2.23 on 2025-08-30 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_id", models.CharField(max_length=30, unique=True)),
                ("asin", models.CharField(max_length=20)),
                ("item_name", models.CharField(max_length=255)),
                ("customer_name", models.CharField(blank=True, max_length=255)),
                ("customer_email", models.EmailField(blank=True, max_length=254)),
                ("order_data", models.DateTimeField(blank=True, null=True)),
                (
                    "order_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
            ],
        ),
    ]
